name: C++ WebAssembly CI

on:
  pull_request:
    branches: [main, develop]

jobs:
  lint:
    name: Linting
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install clang-format and clang-tidy
        run: |
          sudo apt-get update
          sudo apt-get install -y clang-format clang-tidy

      - name: Check code formatting with clang-format
        run: |
          find . -name "*.cpp" -o -name "*.hpp" -o -name "*.c" -o -name "*.h" | \
          xargs clang-format --dry-run --Werror

      - name: Run clang-tidy static analysis
        run: |
          if [ ! -f compile_commands.json ]; then
            echo "Warning: compile_commands.json not found. Skipping clang-tidy."
            echo "Consider using bear or cmake to generate compile_commands.json"
            exit 0
          fi

          find . -name "*.cpp" -o -name "*.c" | \
          xargs clang-tidy --config-file=.clang-tidy || echo "clang-tidy completed with warnings"

  build:
    name: Build WebAssembly
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Emscripten
        uses: mymindstorm/setup-emsdk@v14
        with:
          version: latest

      - name: Verify Emscripten installation
        run: |
          emcc --version
          which emcc

      - name: Make dev script executable
        run: chmod +x ./dev.sh

      - name: Run build script
        run: ./dev.sh
